### ISSUE TITLE
BetterPipes causes connection issues.

### ISSUE THREAD

**Issue by border999** [flyingperson23/BetterPipes#2]
I've been trying to narrow down what's causing a number of my mods cables, pipes, conduits, etc. to not connect properly under normal circumstances. Found it here.

**Comment by border999** [comment]
![Screenshot (318)](https://user-images.githubusercontent.com/11824584/107780321-a1585580-6cea-11eb-879c-b7a5e30490c2.png)
![Screenshot (317)](https://user-images.githubusercontent.com/11824584/107780327-a3baaf80-6cea-11eb-9ccc-73a7153fe8be.png)
![Screenshot (321)](https://user-images.githubusercontent.com/11824584/107780375-b2a16200-6cea-11eb-8142-7784c1710ac7.png)
![Screenshot (326)](https://user-images.githubusercontent.com/11824584/107780430-c056e780-6cea-11eb-9e94-9d220babb918.png)
![Screenshot (322)](https://user-images.githubusercontent.com/11824584/107780439-c2b94180-6cea-11eb-9ed7-b0511a9f7fc9.png)
![Screenshot (323)](https://user-images.githubusercontent.com/11824584/107780445-c3ea6e80-6cea-11eb-80e9-42fc051671bb.png)
![Screenshot (324)](https://user-images.githubusercontent.com/11824584/107780452-c5b43200-6cea-11eb-8dc6-fd5395cfa775.png)
![Screenshot (325)](https://user-images.githubusercontent.com/11824584/107780454-c6e55f00-6cea-11eb-9c03-8f78b33a1ef7.png)

**Comment by flyingperson23** [comment]
That looks like exactly what it's supposed to do. Do you know how gt6 pipes work? Try holding a wrench and looking at the pipes. You can connect them that way or they automatically connect if you place them on each other.

**Comment by border999** [comment]
Does that include stuff like energy transferring? Because I can't get mekanism conduits to transfer energy.
